=== namanchrist/WSD_PROJECT/atat_xsd.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Root element -->
    <xs:element name="html">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="head" type="headType"/>
                <xs:element name="body" type="bodyType"/>
            </xs:sequence>
            <xs:attribute name="lang" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Head element -->
    <xs:complexType name="headType">
        <xs:sequence>
            <xs:element name="meta" type="metaType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="link" type="linkType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="script" type="scriptType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Meta element -->
    <xs:complexType name="metaType">
        <xs:attribute name="charset" type="xs:string"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="content" type="xs:string"/>
        <xs:attribute name="viewport" type="xs:string"/>
    </xs:complexType>

    <!-- Link element -->
    <xs:complexType name="linkType">
        <xs:attribute name="rel" type="xs:string"/>
        <xs:attribute name="href" type="xs:string"/>
        <xs:attribute name="crossorigin" type="xs:string"/>
        <xs:attribute name="type" type="xs:string"/>
    </xs:complexType>

    <!-- Script element -->
    <xs:complexType name="scriptType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="src" type="xs:string"/>
                <xs:attribute name="crossorigin" type="xs:string"/>
                <xs:attribute name="async" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- Body element -->
    <xs:complexType name="bodyType">
        <xs:sequence>
            <xs:element name="div" type="divType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Div element -->
    <xs:complexType name="divType">
        <xs:sequence>
            <xs:element name="div" type="divType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="h1" type="xs:string" minOccurs="0"/>
            <xs:element name="h2" type="xs:string" minOccurs="0"/>
            <xs:element name="h3" type="xs:string" minOccurs="0"/>
            <xs:element name="h4" type="xs:string" minOccurs="0"/>
            <xs:element name="h5" type="xs:string" minOccurs="0"/>
            <xs:element name="p" type="pType" minOccurs="0"/>
            <xs:element name="img" type="imgType" minOccurs="0"/>
            <xs:element name="a" type="aType" minOccurs="0"/>
            <xs:element name="ul" type="ulType" minOccurs="0"/>
            <xs:element name="li" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="i" type="iType" minOccurs="0"/>
            <xs:element name="iframe" type="iframeType" minOccurs="0"/>
            <xs:element name="hr" type="xs:anyType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="class" type="xs:string"/>
    </xs:complexType>

    <!-- Paragraph element -->
    <xs:complexType name="pType">
        <xs:sequence>
            <xs:element name="b" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="i" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="a" type="aType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="small" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Anchor element -->
    <xs:complexType name="aType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="href" type="xs:string"/>
                <xs:attribute name="target" type="xs:string"/>
                <xs:attribute name="rel" type="xs:string"/>
                <xs:attribute name="class" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- Image element -->
    <xs:complexType name="imgType">
        <xs:attribute name="src" type="xs:string" use="required"/>
        <xs:attribute name="width" type="xs:string"/>
        <xs:attribute name="height" type="xs:string"/>
        <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>

    <!-- Iframe element -->
    <xs:complexType name="iframeType">
        <xs:attribute name="src" type="xs:string" use="required"/>
        <xs:attribute name="allowfullscreen" type="xs:string"/>
        <xs:attribute name="loading" type="xs:string"/>
        <xs:attribute name="referrerpolicy" type="xs:string"/>
        <xs:attribute name="class" type="xs:string"/>
    </xs:complexType>

    <!-- List elements -->
    <xs:complexType name="ulType">
        <xs:sequence>
            <xs:element name="li" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Italics element -->
    <xs:complexType name="iType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="class" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== namanchrist/WSD_PROJECT/atat2.xml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="atat_xsd.xsd" lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Annapurna Tour and Travels</title>
        <link rel="stylesheet" href="style.css" />
        <script src="https://kit.fontawesome.com/e2be1e8079.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css2?family=Lugrasimo&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Platypi:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Rubik+Iso&display=swap" rel="stylesheet" />
    </head>
    <body> 
        <div class="header">
            <div class="container">
                <div class="navbar"> 
                    <div class="logo">
                        <a href="file:///Users/anirbanbanerjee/Desktop/atat.html"><img src="Location pictures/atat_logo.jpg" width="350px" height="80px" /></a>
                    </div>
                    <nav>
                        <ul id="MenuItems">
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Reviews</a></li>
                            <li><a href="sign_in.html#" target="_blank" rel="noopener noreferrer">Login</a></li>
                        </ul>
                    </nav>
                    <div class="menu">
                        <i class="fa fa-bars" onclick="menutoggle()"></i>
                    </div>
                </div>
                <div class="row">
                    <div class="col-2">
                        <h1>Travel the world</h1>
                        <p>Iss do din ke zindagi ko sawaar lo</p>
                        <a href="portfolio.html" class="btn" target="_blank" rel="noopener noreferrer">Explore more &#8594;</a>
                    </div>
                    <div class="col-2">
                        <img src="Location pictures/scenery.jpeg" style="border-radius:10px;" /> 
                    </div>
                </div><br> 
            </div>
        </div>
        <!-- features -->
        <div class="categories">
            <div class="small-container">
                <div class="row">
                    <div class="col-3">
                        <img src="Location pictures/andaman.jpg" />
                    </div>
                    <div class="col-3">
                        <img src="Location pictures/haridwar.jpg" />
                    </div>
                    <div class="col-3">
                        <img src="Location pictures/mumbai.jpg" />
                    </div>
                </div>
            </div>
        </div>
        <div class="small-container">
            <h2 class="title">Featured locations</h2>
            <div class="row">
                <div class="col-4">
                    <img src="Location pictures/puri.jpg" />
                    <h4><b>Puri</b></h4>
                    <p>for 6 days</p>
                    <div class="rating">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-half-o"></i>
                    </div>
                </div>
                <div class="col-4">
                    <img src="Location pictures/kashmir.jpg" />
                    <h4><b>Kashmir</b></h4>
                    <p>for 16 days</p>
                    <div class="rating">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-o"></i>
                    </div>
                </div>
                <div class="col-4">
                    <img src="Location pictures/andaman_1.jpg" />
                    <h4><b>Andaman</b></h4>
                    <p>for 8 days</p>
                    <div class="rating">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-half-o"></i>
                    </div>
                </div>
                <div class="col-4">
                    <img src="Location pictures/mumbai_1.jpg" />
                    <h4><b>Mumbai</b></h4>
                    <p>for 18 days</p>
                    <div class="rating">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-half-o"></i>
                        <i class="fa fa-star-o"></i>
                    </div>
                </div>
            </div>
        </div>
        <!-- offer -->
        <div class="offer">
            <div class="small-container">
                <div class="row">
                    <div class="col-2">
                        <img src="Location pictures/puri.jpg" />
                    </div>
                    <div class="col-2">
                        <p><b>Most popular on Annapurna Tours</b></p>
                        <h1>Puri</h1>
                        <small>Enjoy 6 nights and 5 days by the ecstatic beach of Puri along with the residence of the lord of the Universe. Also, experience the Royal Bengals of <b>Nandankanan </b>and the infamous <b>Konark Sun Temple</b>.<br></small>
                        <a href="file:///Users/anirbanbanerjee/Desktop/portfolio.html" class="btn">Book Now &#8594;</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="testimonial">
            <div class="small-container">
                <div class="row">
                    <div class="col-3">
                        <i class="fa fa-quote-left"></i>
                        <p>The food served here is better than any restaurant I've eaten in! Although it was a little hectic but, in the end, everything was worth it.</p>
                        <div class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-o"></i>
                        </div>
                        <img src="Location pictures/Mayukh.jpeg" />
                        <h3>Mayukh Ghosh</h3>
                    </div>
                    <div class="col-3">
                        <i class="fa fa-quote-left"></i>
                        <p>Every time our eyes blink, is a moment missed. Great arrangements and good company too. Nothing illustrous about it.</p>
                        <div class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                        <img src="Location pictures/Vidushi.jpeg" />
                        <h3>Vidushi Kaushik</h3>
                    </div>
                    <div class="col-3">
                        <i class="fa fa-quote-left"></i>
                        <p>Trustworthy and well-behaved staff members to help me whenever needed, be it carrying my bags or bringing food to my room.</p>
                        <div class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-half-o"></i>
                        </div>
                        <img src="Location pictures/Ananya.jpeg" />
                        <h3>Ananya Chowdhury</h3>
                    </div>
                </div> 
            </div>
        </div>
        <div class="categories">
            <div class="small-container">
                <div class="row">
                    <div class="col-2">
                        <iframe class="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d103698.46820893977!2d86.10462402613491!3d19.804695963472155!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a19aa54d20f2cf7%3A0x9dfab99b5f00ab65!2sPuri%2C%20Odisha!5e0!3m2!1sen!2sin!4v1692608226660!5m2!1sen!2sin" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="footer-col-1">
                        <h3>Download our app</h3>
                        <p>Download our app for Android and iOS mobile phone.</p>
                        <div class="app-logo">
                            <img src="Location pictures/play-store.png" />
                            <img src="Location pictures/app-store.png" />
